### ISSUE TITLE
Question about error in code

### ISSUE THREAD

**Issue by krazzarkov** [L1lykn1ght/Drift-Arb#1]
Hello,

I stumbled across your repo by accident. I am currently making a similar arb bot between Drift and FTX and wanted to try and test out your implementation for ideas. 

Unfortunately, I wasn't able to run the bot and also got an error inside the code as well:

![image](https://user-images.githubusercontent.com/8461672/160028296-bcf925ea-3e64-49fe-b30b-80a220d1d218.png)

I wasn't able to fix this issue so I was curious if you knew what the problem could be.

Thank you in advance! :)

**Comment by L1lykn1ght** [comment]
I forgot to modify it to match the latest drift sdk.
Please change `await pythClient.getPriceData(MarketAccount.amm.oracle)` to `await pythClient.getOraclePriceData(MarketAccount.amm.oracle)`
I think it will work !

By the way, Drift-Arb is a bit complicated code, so please also refer to [Drift-Client](https://github.com/L1lykn1ght/Drift-Client), which is easier to understand. The contents are the same.

**Comment by krazzarkov** [comment]
Thank you for the prompt response, that fixed the issue with the code and I saw you also pushed a commit to update it as well.

Unfortunately, I am still having issues running the script using `node example.ts`
![image](https://user-images.githubusercontent.com/8461672/160036749-9eb6c6f1-3aca-4f2f-bad4-8dc8f03036c9.png)

I'm not sure if this is an issue on my end. I tried modifying the package.json as well as adding ts-node to the package.json but wasn't able to get it to work. Will try and figure out the issue when I get some more time.

As for [Drift-Client](https://github.com/L1lykn1ght/Drift-Client), from a brief look, it seems like you are trying to arb between Drift and Binance instead of FTX? 

I'm not sure if you have a Twitter or Discord but would love to get in touch with you since I am trying to build out a very similar system :)

Thank you again!!

**Comment by L1lykn1ght** [comment]
`node example.ts` is not right command. `node example.js` is the right command.
I forgot to write this one, `node example.js` code is not working if there is no javascript file(example.js). So, to create example.js file, please execute `tsc example.ts` command. If you can see example.js file, then `node example.js` will work I think.

Drift-Client has been updated to allow arbitrage with Binance as well. Because FTX will not be available in my region from April...

My discord account is Lilyknight#1529. Im in the Drift Protocol Discord, so feel free to contact me 👍

**Comment by krazzarkov** [comment]
Thanks for getting back to me

I originally thought you made a type in your README but I didn't realize you could just generate the Javascript file using tsc. 

I generated it and got it to work :)

Thank you for your help
